version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/:/var/lib/mysql

  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./:/usr/src/app
  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 2000:80
  #   environment:
  #     - PMA_ARBITRARY=1